[tox]
skipsdist = True
envlist = py39

[testenv]
deps = -rtest_requirements.txt

[testenv:pytest]
commands = python -m pytest test/ -v --tb=short

[testenv:pylint]
allowlist_externals = bash
commands = bash -c 'pylint -f parseable limiter test | tee pylint.out'
